name = "short-linker"
type = "javascript"

account_id = CF_ACCOUNT_ID
workers_dev = true
compatibility_date = "2021-10-19"
route = ""
zone_id = ""
kv_namespaces = [
    { binding = "URL_SPACE", id = "9140390fc16c47f981b7010f893a418c"}
]
